services:
 database:
   image: postgres:latest
   container_name: postgres_db
   ports:
       - "5432:5432"
   environment:
     POSTGRES_USER: admin
     POSTGRES_PASSWORD: admin
     POSTGRES_DB: backend
   volumes:
     - ./data/postgres:/var/lib/postgresql/data

