# Stage 1: build with JDK 21
FROM maven:3.9.6-eclipse-temurin-21 AS build
WORKDIR /app
COPY pom.xml .
COPY src ./src
RUN mvn clean package -DskipTests

# Stage 2: runtime with JDK 21
FROM eclipse-temurin:21-jdk-jammy
WORKDIR /app
COPY --from=build /app/target/ecom-0.0.1-SNAPSHOT.jar app.jar
EXPOSE 7878
ENTRYPOINT ["java","-jar","app.jar"]
