logging:
  level:
    ROOT: INFO
    org.hibernate.SQL: INFO          # Only show executed SQL
    org.springframework.security: INFO   # Hide TRACE/DEBUG from Spring Security
    com.lnr.ecom: DEBUG              # Still see your app’s debug logs
    org.apache.hc.client5.http: INFO


spring:
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

  profiles:
    active: local

